### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by edumaciel10** [edumaciel10/avl-tree-games#1]
First steps
- [x] Create a simple main that implements a simple test of insert in AVL tree
- [x] Add existent structure of the game
- [x] Create an AVL tree structure that balance all nodes in each new node

Final steps
- [x] Add functions to delete games
- [x] Fix the games struct ("empresa" and "nome" should be dynamically allocated)
